### ISSUE TITLE
Screams from Within's second ability (Return ~ to your hand) does not function. 

### ISSUE THREAD

**Issue by jmeka** [PennyDreadfulMTG/modo-bugs#234]
![capture](https://user-images.githubusercontent.com/28836887/33646512-e58672cc-da1d-11e7-92ef-050ac93e2614.JPG)

Kalastria Healer was targetted with Screams from Within, then sacrificed to Bloodthrone Vampire.

Affects: [Screams from Within]
 <img src="https://api.scryfall.com/cards/named?exact=Screams%20from%20Within&format=image" width="300px">

**Comment by BackAlleyG** [comment]
Fixed in build notes of [ June 5th announcements](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-june-05-2018-2018-06-05).

>Screams from Within will correctly return to your hand when the creature it's enchanting dies.

It does work correctly now even though there was an error in the fix entry of where it comes back to. I checked.

![image](https://user-images.githubusercontent.com/31076829/41114323-19272d00-6a52-11e8-945a-2c9531c7cf99.png)
