### ISSUE TITLE
Lurking Evil makes you pay life equal to half of your opponent's life total

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#237]
Spotted on [Reddit](https://www.reddit.com/r/MTGO/comments/7k1gf5/lurking_evil_mtgo_bug_avoid_in_vintage_masters/) by /u/IKill4Cash and /u/jeffderek

Screenshots: https://imgur.com/a/nZcuh
Affects: [Lurking Evil]
 <img src="https://pennydreadfulmagic.com/image/Lurking%20Evil/" height="300px">

**Comment by suoverg** [comment]
Seems to work fine now

**Comment by silasary** [comment]
Thanks 😄

**Comment by suoverg** [comment]
So after playing with Lurking Evil some more I've discovered that it is
still very bugged, but it doesn't take from your opponent's life total as
in the previous bug report. The ability activation does take from your life
total, but it takes a random amount instead of half, sometimes. Also, the
ability can't even be activated sometimes, seemingly randomly.

**Comment by silasary** [comment]
Please confirm if the "random amount" is in fact half of your opponent's life total. 

The bug is that you lose half of your opponent's life total instead of half of your own. 

Eg: If I am on 12, and my opponent is on 20, the cost will make me pay 10 life, rather than the 6 that you'd expect. 

I may need to reword the summary if that wasn't clear.
