### ISSUE TITLE
Dosan the Falling Leaf only allows players to cast spells during their opponents' turn

### ISSUE THREAD

**Issue by Rowsol** [PennyDreadfulMTG/modo-bugs#290]
Affects: [Dosan the Falling Leaf]
 <img src="https://api.scryfall.com/cards/named?exact=Dosan%20the%20Falling%20Leaf&format=image" width="300px">

**Comment by silasary** [comment]
What about opponents?

**Comment by Rowsol** [comment]
In hindsight I would've waited to see but I conceded as soon as I noticed the issue.

**Comment by stash86** [comment]
So instead of making players only be able to cast spells during their own turn, Dosan make players only able to cast spells during their opponent's turn, which means you can only play instants for the rest of the game, unless you are playing madness deck. And even if you are on madness deck, you can't cast any madness card if it's your turn. You can only cast madness cards if it's discarded in your opponent's turn

**Comment by Rowsol** [comment]
Haha, thanks for testing.  That's pretty funny.

**Comment by BackAlleyG** [comment]
[Here's a video](https://youtu.be/M4uB49eCP1I?t=7m6s)

**Comment by BackAlleyG** [comment]
Fixed in build notes of [May 1st announcements](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-may-01-2018).

>Dosan the Falling Leaf now functions correctly.
