### ISSUE TITLE
Cards exiled by Cast Out are not placed underneath it

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/modo-bugs#320]
**What is the expected behaviour of the card?**
 - Permanent exiled by Cast Out will be placed underneath it in grayed out visual

**What is the actual behaviour of the card?**
 - The exiled permanent doesn't placed underneath it
Reported by a reddit user https://www.reddit.com/r/MTGO/comments/82tnso/cast_out_glitch/

**Screenshot**
(Attach a screenshot or video here)

**Please provide a list of affected cards**
Affects: [Cast Out]

**Card Images**
 <img src="https://api.scryfall.com/cards/named?exact=Cast%20Out&format=image" width="300px">

**Comment by bricarp** [comment]
Cast Out works fine normally when exiling a card that my opponent owns and controls. I want to point out that this glitch is specifically for cards that **I own**, but did not control. (For example, because the opponent used Hostage Taker.)

I'm unclear if the exiled permanent will return to the battlefield when Cast Out is destroyed. I have not been able to test that.

**Comment by silasary** [comment]
Hexalite has reported this as fixed
