### ISSUE TITLE
Mystic Forge does not allow casting Zoetic Cavern as a Morph creature from the top of your library

### ISSUE THREAD

**Issue by f7eleven** [PennyDreadfulMTG/modo-bugs#768]
**What is the expected behaviour of the card?**
 - To be able to play Morph creatures from the top of your library

**What is the actual behaviour of the card?**
 - You cannot play Zoetic Cavern as a Morph creature from the top of your library

**Screenshot**
Currently Unconfirmed.

**Please provide a list of affected cards**
Affects: [Mystic Forge]
See Also: [Zoetic Cavern]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Mystic%20Forge/" height="300px"><img src="https://pennydreadfulmagic.com/image/Zoetic%20Cavern/" height="250px">

**Comment by tsutton** [comment]
This is the intended behavior. Mystic Forge gives you permission to cast cards from an unusual place only if they are artifacts or colorless nonlands. The rule for morph is as follow, emphasis mine

702.36a **Morph is a static ability that functions in any zone from which you could play the card it’s
on,** and the morph effect works any time the card is face down. “Morph [cost]” means “You
may cast this card as a 2/2 face-down creature with no text, no name, no subtypes, and no mana
cost by paying {3} rather than paying its mana cost.” (See rule 707, “Face-Down Spells and
Permanents.”)

Since you do not have permission to play Zoetic Cavern from your deck, its morph ability does not function.

**Comment by emerald000** [comment]
That's wrong. Morphs are flipped face-down before checking for casting legality.

702.36c. To cast a card using its morph ability, turn it face down. It becomes a 2/2 face-down creature card with no text, no name, no subtypes, and no mana cost. Any effects or prohibitions that would apply to casting a card with these characteristics (and not the face-up card's characteristics) are applied to casting this card. [...]

There's an example with a similar effect at: http://www.cranialinsertion.com/article/619#q20

**Comment by tsutton** [comment]
That article seems to be in contradiction toe the rules, even to part of 702.36c which you omitted: "You can use a morph ability to cast a card from any zone from which you could normally play
it. When the spell resolves, it enters the battlefield with the same characteristics the spell had."

Rather than argue over an article from 2012(!!) and my interpretation of the rules as they sit in 07/2019, I will ping the judge chat.

**Comment by emerald000** [comment]
I am a L2 judge and that's how it works. 

The first part of 702.36c says you apply effects to the face-down card, not the face-up. Which means the second part means if an effect lets you cast a card from another zone applies to the face-down morph, not the face-up card.

**Comment by tsutton** [comment]
Reopening! TIL. I think 702.36a is very misleading, then, since it seems to be suggesting that you should check the card as-is, not face down.

**Comment by f7eleven** [comment]
There's also a ruling on gatherer for mystic forge stareting you can play
any morph with mystic forge.

**Comment by bakert** [comment]
<img width="1267" alt="image" src="https://github.com/user-attachments/assets/53eeed2a-658f-48e2-9b05-c92e58d2ffa4">

This has been fixed.
